check_for_stray_static_libs:             0.0000 sec
check_for_stray_las:                     0.0000 sec
check_ruby_version:                      0.0000 sec
check_for_stray_pcs:                     0.0000 sec
check_for_symlinked_cellar:              0.0000 sec
check_for_stray_dylibs:                  0.0000 sec
check_multiple_cellars:                  0.0000 sec
check_for_stray_headers:                 0.0000 sec
check_for_other_frameworks:              0.0000 sec
check_homebrew_prefix:                   0.0000 sec
check_exist_directories:                 0.0000 sec
check_for_git:                           0.0000 sec
check_if_xcode_needs_clt_installed:      0.0000 sec
check_casktap_integrity:                 0.0000 sec
check_for_unsupported_macos:             0.0000 sec
check_for_pydistutils_cfg_in_home:       0.0000 sec
check_for_iconv:                         0.0000 sec
check_cask_install_location:             0.0000 sec
check_cask_staging_location:             0.0001 sec
check_cask_load_path:                    0.0001 sec
check_filesystem_case_sensitive:         0.0001 sec
check_coretap_integrity:                 0.0001 sec
check_cask_environment_variables:        0.0001 sec
check_clt_minimum_version:               0.0001 sec
check_git_version:                       0.0001 sec
check_if_supported_sdk_available:        0.0001 sec
check_deprecated_caskroom_taps:          0.0002 sec
check_for_external_cmd_name_conflict:    0.0002 sec
check_deprecated_official_taps:          0.0002 sec
check_access_directories:                0.0004 sec
check_for_tap_ruby_files_locations:      0.0006 sec
check_cask_taps:                         0.0007 sec
check_for_non_prefixed_coreutils:        0.0009 sec
check_for_non_prefixed_findutils:        0.0010 sec
check_cask_software_versions:            0.0046 sec
check_cask_xattr:                        0.0047 sec
check_for_installed_developer_tools:     0.0050 sec
check_for_gettext:                       0.0083 sec
check_clt_up_to_date:                    0.0112 sec
check_for_multiple_volumes:              0.0144 sec
check_for_unlinked_but_not_keg_only:     0.0174 sec
check_for_unnecessary_core_tap:          0.0190 sec
check_git_newline_settings:              0.0203 sec
check_for_unnecessary_cask_tap:          0.0212 sec
check_broken_sdks:                       0.0263 sec
check_for_unreadable_installed_formula:  0.0345 sec
check_git_status:                        0.0439 sec
check_brew_git_origin:                   0.0447 sec
check_tap_git_branch:                    0.0654 sec
check_deprecated_disabled:               0.2032 sec
check_cask_quarantine_support:           0.2113 sec
check_deleted_formula:                   0.6871 sec
brew update && brew upgrade && brew cleanup && brew doctor --audit-debug
